### ISSUE TITLE
 FilterRow don't work with ExtJS 3.3.0

### ISSUE THREAD

**Issue by darklow** [nene/filter-row#1]
Unfortunately: FilterRow don't work with ExtJS 3.3 - http://triin.net/temp/filter-row/
Sencha forums: http://www.sencha.com/forum/showthread.php?112346-Which-extensions-plugins-are-not-compatible-with-Ext-3.3&highlight=FilterRow
Could you please help us find the fix?
Thanks.

**Comment by shivaaqua** [comment]
Adding the following code will fix the issue       <br /> 
 <code> grid.getView().on("refresh", this.renderFields, this); </code>

**Comment by darklow** [comment]
Thanks. Now it works fine!

**Comment by nene** [comment]
That makes it better, but doesn't fully fix though.

Because all the fields in header are re-rendered you will lose focus. e.g. after each character you type to the filter field you have to refocus the field.

**Comment by nene** [comment]
Fixed. Basically just like shivaaqua suggested + quite a bit extra code to restore the focus in field.
